### ISSUE TITLE
复现工作遇到了数据集问题

### ISSUE THREAD

**Issue by 1137292294** [Hannibal046/SelfMemory#1]
您好，我最近在复现您的实验，遇到了一些数据集问题，JRC-Acquis数据集解压完是txt的格式，大概怎么处理成您要求的jsonl格式，有点没有思路

**Comment by Hannibal046** [comment]
你好,不同的数据集需要不同的key,比如JRC-Acquis En-De:
https://github.com/Hannibal046/SelfMemory/blob/58d8b611ad51605091c7555c0f32dce6702dadbf/src/config/jrc_ende/train_generator.yaml#L7-L8

**Comment by 1137292294** [comment]
可能是我没太懂您的意思，我目前的操作是把数据集下载下来并按照您提供的script处理了数据得到
![image](https://github.com/Hannibal046/SelfMemory/assets/80505938/87c168c4-143e-476f-95be-553f777baa2b)
然后我就不知道下一步我该做什么了，不好意思给您添麻烦了

**Comment by Hannibal046** [comment]
数据的读取逻辑在这个地方:
https://github.com/Hannibal046/SelfMemory/blob/58d8b611ad51605091c7555c0f32dce6702dadbf/src/train_generator.py#L47-L107

输入就是一个jsonl文件,key是config文件里面对应的src和trg

**Comment by FreshPrincePerseus** [comment]
作者您好，我正在尝试在bigPatent数据集上复现您的实验。在数据处理时，您说需要将数据集处理成jsonl格式。请问我是需要将train数据集中的所有部分(a、b、c... )以及它们内部所包含的所有子文件(例如data0000000000xx.gz)中的所有数据解压后都存入一个单独的train.jsonl文件吗？test、val数据集是不是也需要同样的做法呢？
希望作者能够解答疑惑，谢谢。

**Comment by Hannibal046** [comment]
是的,需要放入同一个jsonl文件

这是最后的statistic:
![image](https://github.com/Hannibal046/SelfMemory/assets/38466901/6c0bf7bb-6951-4920-aff1-30bc676d524b)

**Comment by freezed-corpse-143** [comment]
> 可能是我没太懂您的意思，我目前的操作是把数据集下载下来并按照您提供的script处理了数据得到 ![image](https://private-user-images.githubusercontent.com/80505938/317171634-87c168c4-143e-476f-95be-553f777baa2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDUyNDgsIm5iZiI6MTcyOTA0NDk0OCwicGF0aCI6Ii84MDUwNTkzOC8zMTcxNzE2MzQtODdjMTY4YzQtMTQzZS00NzZmLTk1YmUtNTUzZjc3N2JhYTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAyMTU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMzZlZTUxYjQ0NmZlZmE3YTdhZmE0NDMzNzBiMGQ0YmMyZWQ0NDY0M2ZiOWYwYTFmMWUzZThlNjYxOTdkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.regM1WpvoHK8iqkRyH_17VqpueBNxobXOnVTOYki3js) 然后我就不知道下一步我该做什么了，不好意思给您添麻烦了

我也遇到了这个问题，请问解决了吗？

**Comment by freezed-corpse-143** [comment]
{"context": ["你好", "今天天气怎么样？", "很好，谢谢。"], "persona": ["我是一名程序员。", "我喜欢编程。"]}
{"context": ["你叫什么名字？", "我叫小明。", "你好，小明。"], "persona": ["我是一名教师。", "我喜欢教书。"]}

**Comment by freezed-corpse-143** [comment]
根据代码反推读取jsonl文件的数据格式如下：
{"context": ["你好", "今天天气怎么样？", "很好，谢谢。"], "persona": ["我是一名程序员。", "我喜欢编程。"]}
{"context": ["你叫什么名字？", "我叫小明。", "你好，小明。"], "persona": ["我是一名教师。", "我喜欢教书。"]}

**Comment by freezed-corpse-143** [comment]
找源码找出格式信息了：prepare.py生成train.txt文件，其中最重要的一句是：fo.write(' '.join(src_line) + '\t' + ' '.join(tgt_line) + '\n')。train.txt文件每行前面是源语言，后面是目标语言，中间以\t间隔。prepare.sh生成dev.txt和test.txt，其中最重要的一句是：paste -d '\t' ${main}/deen/dev/jrc.dev.tgt ${main}/deen/dev/jrc.dev.src > ${out}/ende/dev.txt。同样test.txt和dev.txt每行同样是前面是目标语言，后面是源语言，中间以\t间隔

**Comment by freezed-corpse-143** [comment]
> 你好,不同的数据集需要不同的key,比如JRC-Acquis En-De:
> 
> https://github.com/Hannibal046/SelfMemory/blob/58d8b611ad51605091c7555c0f32dce6702dadbf/src/config/jrc_ende/train_generator.yaml#L7-L8
 
我懂了，对train.txt，dev.txt，test.txt做如下处理，依次读取每行，以\t分割为src和tgt两部分，每个部分再以" "分割成列表，然后输出为以下格式{“src": [1,3,4], "tgt":[4,5,5]},不需要关心context和persona部分
