### ISSUE TITLE
关于整个流程的问题

### ISSUE THREAD

**Issue by babyporgrammer** [Hannibal046/SelfMemory#12]
作者你好，感谢你的工作，我在复现的时候有如下几个问题，麻烦帮忙解答：
1 训练selector的时候，memory的生成仅来源于generator的一次生成吗?或者是对于翻译任务中的同一条数据，流程如下：generator 生成candidates -> 根据candidates训练一次selector，并且选择一个memory -> generator 根据选择的memory + source 再进行第二次candidate生成 -> 重复以上步骤直至收敛。

2在伪代码中，提到的在validation set进行收敛，是指的训练selector进行收敛吗? 还是指memory set 所需要的iteration轮数呢？
![image](https://github.com/user-attachments/assets/b885ed80-ee18-45b6-a009-66bb0bbb8fcc)

3 在最终推理的时候，我理解的是需要进行一定iteration的迭代来获取最终的memory的，那么我如何确定在什么时候停止迭代呢？

再次感谢作者的解答

**Comment by Hannibal046** [comment]
你好,
1. 一次生成
2. 在validation set上确定迭代轮数
3. 根据2

**Comment by babyporgrammer** [comment]
理解了，感谢作者的解答
