### ISSUE TITLE
复现时在调用预训练模型时遇到了问题

### ISSUE THREAD

**Issue by qinghaojun** [Hannibal046/SelfMemory#2]
我将bartbase模型下载后所有文件都保存到../pretrained_model/transformer_base_jrc_ende文件夹下，但是仍然报错 
raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../pretrained_model/transformer_base_jrc_ende'. Use `repo_type` argument if needed.

Traceback (most recent call last):
  File "train_generator.py", line 478, in <module>
    model = ConditionalGenerator(**vars(args))
  File "train_generator.py", line 160, in __init__
    self.configure_model()
  File "train_generator.py", line 177, in configure_model
    self.tokenizer = AutoTokenizer.from_pretrained(self.hparams.pretrained_model_path)

可以麻烦您更新一下/pretrained_model文件夹内的内容吗

**Comment by Hannibal046** [comment]
你好,pretrained_model里面的内容是预训练的模型,没办法更新在git上,可以在huggingface上下载.

**Comment by AiMijie** [comment]
你好。请问能否提供各个模型的下载链接？如何准确搜索到repo里使用的模型？
