### ISSUE TITLE
memory的数据结构是什么样子的？

### ISSUE THREAD

**Issue by cows21** [Hannibal046/SelfMemory#3]
以这个命令行为例：
## Transformer-Joint
python train_generator.py \
    --config config/jrc_ende/train_generator.yaml \
    --precision 16 \
    --memory_encoding concate \
    --memory_dir ../data/jrc_ende/memory/bm25 

请问memory_dir ../data/jrc_ende/memory/bm25 路径内的memory应该是什么样的？从作者在Memory Selector提供的命令行参数设定来看，memory应该存在类似于“test.txt”的文件中？我之前在下载jrc数据集时，使用了作者推荐的脚本，得到了一系列的文件夹{ende,deen,enes,esen}，每个文件夹里包含{dev.txt, test.txt, train.txt, src.vocab, tgt.vocab}五个文件，我把这些文件夹当作memory文件夹，也即上面的例子中--memory_dir参数我赋值为../data/ende/ 这样设定后程序是能跑的。但是作者在readme中也提到For initial memory retrieval, we use ElasticSearch to conduct first-stage memory retrieval based on BM25 score.我不太明白这句话，我应该如何使用ElasticSearch初始化memory？

我刚刚接触RAG领域，非常感谢作者的工作。希望作者能够解答我的疑问，不胜感激。

**Comment by Hannibal046** [comment]
你好,那个memory是需要通过ElasticSearch在training data里面做检索得到的.
