### ISSUE TITLE
关于复现时遇到的一些问题

### ISSUE THREAD

**Issue by FreshPrincePerseus** [Hannibal046/SelfMemory#5]
作者您好，我正在尝试复现您的实验。但我在尝试运行代码时，碰到了以下问题，希望能够得到您的帮助：
1 您提到`For initial memory retrieval, we use ElasticSearch to conduct first-stage memory retrieval based on BM25 score.`，请问安装了ElasticSearch后需要如何进行使用呢？
2 在`Retrieval-Augmented Generator`的第一步需要`## train a vanilla Transformer model`，我阅读了原文但没有很清楚vanilla Transformer model的作用，希望能请教一下您。
3 在您的代码 ../src/config/bigpatent/train_generator.yaml 中的training部分写明了需要运行在4张卡上，而在其他的数据集yaml文件中则没见这个要求。我在A6000上运行时`python train_generator.py --config config/bigpatent/train_generator.yaml --precision 16`时，如果用两张或者三张跑就会跑一会儿后卡住，只有用单张卡跑才能顺利运行。但是单张卡跑一个epoch需要22个小时，而yaml中max_epochs参数设定为20，这样整体时间看起来就需要很久（也可能与我没有理解vanilla Transformer model有关）。可以问一下您当时使用的设备以及训练时间吗？
4 您在最后Lift Yourself Up部分给出了整个流程的伪代码，请问是需要我在训练好了RAG和Selector之后按照伪代码写一个main来执行吗？
期待您的回复，感谢！

**Comment by Hannibal046** [comment]
你好,
- ElasticSearch只是一个BM25的具体实现,你也可以用其他的搜索引擎,比如Lucene.具体使用方法请参考官网
- Vanilla Transformer是一个作为比较的baseline
- 你说的卡住是什么意思? 当时用的是8*A100进行训练的
- 是的,你可以复用现有的模块,也可以自己写一个

**Comment by FreshPrincePerseus** [comment]
> 你好,
> 
> * ElasticSearch只是一个BM25的具体实现,你也可以用其他的搜索引擎,比如Lucene.具体使用方法请参考官网
> * Vanilla Transformer是一个作为比较的baseline
> * 你说的卡住是什么意思? 当时用的是8*A100进行训练的
> * 是的,你可以复用现有的模块,也可以自己写一个

好的，我按照您的方法尝试一下。卡住是指，当我用2张或者3张A6000 运行`## train a vanilla Transformer model`的命令语句后，在epoch 0 中的进展到 700/106191 左右的时候，训练进展会停止增加（测试的时候发现会连续20分钟没有进展），并且没法通过Ctrl C 来停止训练进程，只能通过关闭终端的方式来停止。

**Comment by Hannibal046** [comment]
你好, 这个框架的分布式是由pytorch-lightning处理的,我并没有碰到你说的这个情况,你可以试着在每个rank上都log,看看卡在哪里了
