### ISSUE TITLE
关于训练Memory Selector部分的提问

### ISSUE THREAD

**Issue by FreshPrincePerseus** [Hannibal046/SelfMemory#6]
作者您好，我想询问一下，在Memory Selector部分，您是用翻译的数据训练好了内存选择器之后，直接迁移使用到其他任务上，还是针对每一个下游任务都单独训练了一个Selector呢？
期待您的答复，感谢！

**Comment by Hannibal046** [comment]
你好,每个任务需要单独训练一个Selector

**Comment by 123THU** [comment]
请问训练Memory Selector时，您使用的base MT model是CNN还是目前这个已经训练成功的generator呀？谢谢！

**Comment by 123THU** [comment]
请问训练Memory Selector时，您使用的base MT model是CNN还是目前这个已经训练成功的generator呀？谢谢！
