### ISSUE TITLE
关于使用训练好的Generator生成candidates的问题

### ISSUE THREAD

**Issue by FreshPrincePerseus** [Hannibal046/SelfMemory#7]
作者您好，在训练预训练模型生成器后，需要生成candidates放入记忆池，执行
```
cd your/work/dir/src
python generate_hyps.py \
	--config config/jrc_ende/generate_hyps.yaml \
    --num_beams 50 --num_return_sequences 50 \
	--data_path ../data/jrc_ende/test.jsonl \
	--pretrained_model_path your/trained/model/path
	--memory_encoding concate \
	--memory_path ../data/jrc_ende/memory/bm25/test.txt \
	--output_path output.txt
```
的操作。这里需要填入 --pretrained_model_path your/trained/model/path ，然而我的预训练模型文件夹下有：bart_large、checkpoints两个文件夹，以及events.out.tfevents、hparams.yaml、test_hyps.txt、test_refs.txt这几个文件。如果我把checkpoints中的.ckpt文件作为预训练模型的地址，会报错说在预训练模型文件夹下没有config.json。我想请教作者这个问题如何解决呢？
期待您的答复～谢谢

**Comment by FreshPrincePerseus** [comment]
还是说，训练后的模型，就储存在/version_x/bart_large文件夹中呢？我查看了SelfMemory/result/generator/concate_bart_large_xsum/lightning_logs/version_x/bart_large/config.json下的配置，发现其architectures参数已经是BartForConditionalGeneration了。

**Comment by Hannibal046** [comment]
你好,代码save chekcpoint的逻辑在这个地方:
https://github.com/Hannibal046/SelfMemory/blob/58d8b611ad51605091c7555c0f32dce6702dadbf/src/train_generator.py#L304-L305
你看下你第一阶段指定的logdir在哪就可以找到了,一般HF model会保存的都是`.pt`或者`.safetensors`

**Comment by FreshPrincePerseus** [comment]
> 你好,代码save chekcpoint的逻辑在这个地方:
> 
> https://github.com/Hannibal046/SelfMemory/blob/58d8b611ad51605091c7555c0f32dce6702dadbf/src/train_generator.py#L304-L305
> 
> 
> 你看下你第一阶段指定的logdir在哪就可以找到了,一般HF model会保存的都是`.pt`或者`.safetensors`

感谢回复！我查看了一下，```
self.model.save_pretrained(os.path.join(log_dir,model_type)) 
 self.tokenizer.save_pretrained(os.path.join(log_dir,model_type)) 
```所在的test_epoch_end函数在train_generator.py中没有被调用，我在复现时也没有指定logdir。请问我是应该在输入执行命令行语句时提前指定好log_dir，然后在train_generator.py最后用trainer调用一下test_epoch_end函数吗？

**Comment by FreshPrincePerseus** [comment]
> 你好,代码save chekcpoint的逻辑在这个地方:
> 
> https://github.com/Hannibal046/SelfMemory/blob/58d8b611ad51605091c7555c0f32dce6702dadbf/src/train_generator.py#L304-L305
> 
> 
> 你看下你第一阶段指定的logdir在哪就可以找到了,一般HF model会保存的都是`.pt`或者`.safetensors`

你好！感谢回复，我检查了我的log_dir地址，发现就是`SelfMemory/result/generator/concate_bart_large_xsum/lightning_logs/version_x`，此外model.save_pretrained的地址也是`/version_x/bart_large`，文件夹中文件如下：
![image](https://github.com/Hannibal046/SelfMemory/assets/121876171/541181f6-c718-4da0-b972-f4c5bb024367)

请问这个pytorch_model.bin是否就是训练好的模型呢？（我没有能找到`.pt`或者`.safetensors`）

**Comment by Hannibal046** [comment]
嗯嗯对的,这个就是训好的模型.
抱歉我记错了,是`.bin`或者`.safetensors`. 你直接load这个可以了
