### ISSUE TITLE
关于训练句子排序器中添加rouge指标的问题

### ISSUE THREAD

**Issue by FreshPrincePerseus** [Hannibal046/SelfMemory#8]
作者您好！在训练句子排序器中，如果是在做摘要任务，需要在fairseq库中添加判断rouge指标情况的代码。我可以请问作者在`fairseq/examples/discriminative_reranking_nmt/tasks/discriminative_reranking_task.py`这个文件中的`class DiscriminativeRerankingNMTTask(FairseqTask)`的`def valid_step(self, sample, model, criterion)`函数中、以及`reduce_metrics(self, logging_outputs, criterion)`函数中是如何写`elif self.cfg.target_metric == "rouge":`的吗？我被这个地方困扰了很久，希望作者能够赐教。谢谢！

**Comment by Hannibal046** [comment]
你好,这个部分的代码我也没有保留,你得自己魔改一下了,我记得需要改的点包括: (1) 更改reranker (2) 更改eval metric (3) 调整相应的训练参数

**Comment by FreshPrincePerseus** [comment]
好的，我在修改中碰到的最大问题在于这里：[https://github.com/facebookresearch/fairseq/blob/d9a627082fd03ec72a27a31a4e56289bfcb2e4e4/examples/discriminative_reranking_nmt/tasks/discriminative_reranking_task.py#L358C3-L363C10](url)，即DrNMT在执行training时，会根据处理bleu和ter指标来设定dummy_target的维度。我想请问您在修改时，还记得对rouge指标维度的设计吗？
