### ISSUE TITLE
关于整个流程拼接部分代码的问题

### ISSUE THREAD

**Issue by FreshPrincePerseus** [Hannibal046/SelfMemory#9]
请问在源码中，有提供将左右两个结构拼接起来的的代码吗？即伪代码中的
```
for _ in range(iteration_k):
    candidates = generator(model_input,memory)
    memory = selector(model_input,candidates)
    hypothesis = generator(model_input,memory)
    current_score = metrics(hypothesis,reference)
```
部分。
期待您的解答，谢谢😃

**Comment by 123THU** [comment]
> 请问在源码中，有提供将左右两个结构拼接起来的的代码吗？即伪代码中的
> 
> ```
> for _ in range(iteration_k):
>     candidates = generator(model_input,memory)
>     memory = selector(model_input,candidates)
>     hypothesis = generator(model_input,memory)
>     current_score = metrics(hypothesis,reference)
> ```
> 
> 部分。 期待您的解答，谢谢😃

您好，请问您这个问题现在得到解决了吗？我看作者好像一直没回复，我现在复现时也遇到了这个问题

**Comment by FreshPrincePerseus** [comment]
> > 请问在源码中，有提供将左右两个结构拼接起来的的代码吗？即伪代码中的
> > ```
> > for _ in range(iteration_k):
> >     candidates = generator(model_input,memory)
> >     memory = selector(model_input,candidates)
> >     hypothesis = generator(model_input,memory)
> >     current_score = metrics(hypothesis,reference)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 部分。 期待您的解答，谢谢😃
> 
> 您好，请问您这个问题现在得到解决了吗？我看作者好像一直没回复，我现在复现时也遇到了这个问题

你好，我后面自己写了一个循环的代码，你也可以试试！但由于我最后一些其他的代码和参数没整明白，我没能复现作者的效果。

**Comment by 123THU** [comment]
感谢您的回复，谢谢！！

**Comment by Hannibal046** [comment]
> > > 请问在源码中，有提供将左右两个结构拼接起来的的代码吗？即伪代码中的
> > > ```
> > > for _ in range(iteration_k):
> > >     candidates = generator(model_input,memory)
> > >     memory = selector(model_input,candidates)
> > >     hypothesis = generator(model_input,memory)
> > >     current_score = metrics(hypothesis,reference)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 部分。 期待您的解答，谢谢😃
> > 
> > 
> > 您好，请问您这个问题现在得到解决了吗？我看作者好像一直没回复，我现在复现时也遇到了这个问题
> 
> 你好，我后面自己写了一个循环的代码，你也可以试试！但由于我最后一些其他的代码和参数没整明白，我没能复现作者的效果。

你好,请问你是在哪个数据集上面做的实验呢? beam search和reranker的结果分别是多少? 如果是翻译任务, 这边在repo里面有提供了完整的bm25_memory, selfmem_memory和输出的hyps: https://github.com/Hannibal046/SelfMemory/tree/main/output/ende

**Comment by FreshPrincePerseus** [comment]
> > > > 请问在源码中，有提供将左右两个结构拼接起来的的代码吗？即伪代码中的
> > > > ```
> > > > for _ in range(iteration_k):
> > > >     candidates = generator(model_input,memory)
> > > >     memory = selector(model_input,candidates)
> > > >     hypothesis = generator(model_input,memory)
> > > >     current_score = metrics(hypothesis,reference)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 部分。 期待您的解答，谢谢😃
> > > 
> > > 
> > > 您好，请问您这个问题现在得到解决了吗？我看作者好像一直没回复，我现在复现时也遇到了这个问题
> > 
> > 
> > 你好，我后面自己写了一个循环的代码，你也可以试试！但由于我最后一些其他的代码和参数没整明白，我没能复现作者的效果。
> 
> 你好,请问你是在哪个数据集上面做的实验呢? beam search和reranker的结果分别是多少? 如果是翻译任务, 这边在repo里面有提供了完整的bm25_memory, selfmem_memory和输出的hyps: https://github.com/Hannibal046/SelfMemory/tree/main/output/ende

作者您好！我是尝试做摘要任务，然后您提到在训练右边的句子排列器时，需要更换评判指标（摘要任务改为rouge）。但是我之前尝试修改时也许是自己的代码能力还不太行，没能改出来，因此右边的结构当时没能实现。后面把循环的代码简单写了一些之后仍然没能搞定右边结构，因此没有能复现。可能我前面的表述不够准确，向您致歉。

**Comment by FreshPrincePerseus** [comment]
我之前尝试做翻译任务时，作者提供的结构是能够成功训练的。因此我认为只要写个循环就能用了。但我自己的方向不在翻译，因此没有继续往下做去跑结果。

**Comment by Hannibal046** [comment]
> 我之前尝试做翻译任务时，作者提供的结构是能够成功训练的。因此我认为只要写个循环就能用了。但我自己的方向不在翻译，因此没有继续往下做去跑结果。

你好,你可以尝试一下使用训好的翻译生成模型,跳过训练判别器, 直接使用repo里面提供的memory文件; 这样也可以看到模型的self-uplift: source + lower_quality_memory --> higher_quality_hyps

**Comment by babyporgrammer** [comment]
> > 我之前尝试做翻译任务时，作者提供的结构是能够成功训练的。因此我认为只要写个循环就能用了。但我自己的方向不在翻译，因此没有继续往下做去跑结果。
> 
> 你好,你可以尝试一下使用训好的翻译生成模型,跳过训练判别器, 直接使用repo里面提供的memory文件; 这样也可以看到模型的self-uplift: source + lower_quality_memory --> higher_quality_hyps

你好，这里提供的memory文件是指从bm25提供最初的memory开始迭代，到最终high quality的memory结束的文件吗？如果是这样的话，我是不是相当于每次只需要将source和不同iteration的memory进行拼接然后输入给generator就可以得到一个逐步提高的结果呢？感谢作者的解答

**Comment by Hannibal046** [comment]
> > > 我之前尝试做翻译任务时，作者提供的结构是能够成功训练的。因此我认为只要写个循环就能用了。但我自己的方向不在翻译，因此没有继续往下做去跑结果。
> > 
> > 
> > 你好,你可以尝试一下使用训好的翻译生成模型,跳过训练判别器, 直接使用repo里面提供的memory文件; 这样也可以看到模型的self-uplift: source + lower_quality_memory --> higher_quality_hyps
> 
> 你好，这里提供的memory文件是指从bm25提供最初的memory开始迭代，到最终high quality的memory结束的文件吗？如果是这样的话，我是不是相当于每次只需要将source和不同iteration的memory进行拼接然后输入给generator就可以得到一个逐步提高的结果呢？感谢作者的解答

你好,这里的bm25_mem是利用source在训练集检索得到的,作为初始memory; selfmem_mem是利用reranker得到的一次迭代结果;如果要实现多轮迭代,需要每次输出N个sample,然后利用reranker挑选.

**Comment by babyporgrammer** [comment]
理解了，感谢作者的解答～

**Comment by FreshPrincePerseus** [comment]
> > > > 我之前尝试做翻译任务时，作者提供的结构是能够成功训练的。因此我认为只要写个循环就能用了。但我自己的方向不在翻译，因此没有继续往下做去跑结果。
> > > 
> > > 
> > > 你好,你可以尝试一下使用训好的翻译生成模型,跳过训练判别器, 直接使用repo里面提供的memory文件; 这样也可以看到模型的self-uplift: source + lower_quality_memory --> higher_quality_hyps
> > 
> > 
> > 你好，这里提供的memory文件是指从bm25提供最初的memory开始迭代，到最终high quality的memory结束的文件吗？如果是这样的话，我是不是相当于每次只需要将source和不同iteration的memory进行拼接然后输入给generator就可以得到一个逐步提高的结果呢？感谢作者的解答
> 
> 你好,这里的bm25_mem是利用source在训练集检索得到的,作为初始memory; selfmem_mem是利用reranker得到的一次迭代结果;如果要实现多轮迭代,需要每次输出N个sample,然后利用reranker挑选.

作者您好，我想请问，您有对测试集做额外操作吗？比如，您用 训练集 + 初始memory 训练了左边的结构。在测试时，您是直接把测试集原输入直接输入训练好的模型，还是将测试集和什么内容拼接后再一起输入模型呢？
